// automatically generated by the FlatBuffers compiler, do not modify

export enum Instruction{
  Heartbeat = 0,
  Handshake = 1,
  PeerConnect = 2,
  PeerDisconnect = 3,
  AreaSubscribe = 4,
  AreaUnsubscribe = 5,
  GlobalMessage = 6,
  LocalMessage = 7,
  RecordCreate = 8,
  RecordRead = 9,
  RecordUpdate = 10,
  RecordDelete = 11,
  RecordReply = 12,
  Unknown = 255
}

