// automatically generated by the FlatBuffers compiler, do not modify

export enum Instruction{
  Heartbeat = 0,
  ZeroMQHandshake = 1,
  ZeroMQPortAssign = 2,
  LocalMessage = 3,
  GlobalMessage = 4,
  RecordCreate = 5,
  RecordRead = 6,
  RecordUpdate = 7,
  RecordDelete = 8,
  RecordReply = 9,
  AreaSubscribe = 10,
  AreaUnsubscribe = 11,
  Unknown = 255
}

