// automatically generated by the FlatBuffers compiler, do not modify

export enum Instruction{
  Heartbeat = 0,
  Handshake = 1,
  LocalMessage = 2,
  GlobalMessage = 3,
  RecordCreate = 4,
  RecordRead = 5,
  RecordUpdate = 6,
  RecordDelete = 7,
  RecordReply = 8,
  AreaSubscribe = 9,
  AreaUnsubscribe = 10,
  Unknown = 255
}

