name: Node.js Publish
on:
  release:
    types: [published]

env:
  NODE_VERSION: 16.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}
      - name: Upgrade Yarn
        run: yarn set version stable
      - name: Install packages
        run: yarn install --immutable
      - name: Publish to NPM
        run: yarn npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
